# Generated by Django 5.2.1 on 2025-06-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_product_delete_book_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('published_year', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
